export const ACTIONS = {

    USER_LOGIN:{
        USER_LOGGING:"LOGGING[USER]",
        USER_LOGGEDIN:"LOGGEDIN[USER]",
        USER_FAIL_LOGIN: "LOGINFAIL[USER]"
    },
    USER_PROFILE:{
        USER_PROFILE_GOT:"GOT[USER_PROFILE]",
        USER_PROFILE_RESET:"RESET[USER_PROFILE]",
    },
}